### ISSUE TITLE
Frameless as real browser / password manager support

### ISSUE THREAD

**Issue by jaanus** [stakes/Frameless#37]
I’ve had word from some people who’d like to use Frameless as a real browser. Which it almost already is. There’s just two things missing.

* URL as omnibox - already planned as enhancement request - #22 
* some sort of password manager support, like 1Password’s great extension

I guess the URL omnibox thing is straightforward and already planned, but wanted to check whether password manager support also supports Frameless product goals. @stakes wdyt?

**Comment by stakes** [comment]
I think it does. I built Frameless, really, to support a prototyping workflow with Framer Studio and the fact that it's supported other (both design-related and general) use cases is a bonus.

Moving forward I want to reposition Frameless as a general-purpose browser, to the point of actually pulling out the few Framer-specific features that I've added. (Us Framer folks won't be left high-and-dry, though, trust me.) So this does fit in with that philosophy.

I don't know too much about password manager integration but if you're interested in partnering up on this and you're familiar with working with 1Password that would be AWESOME :+1: :+1: :+1:

**Comment by stakes** [comment]
Just wanted to close this thread - I've done some thinking about the primary use case and I think I got into it on another issue here... but long story short I've done a complete 180 since my last comment on this thread.

The primary use case for Frameless is going to continue being supporting Framer Studio users, with general web browser functionality secondary to that of the designer using Frameless to preview prototypes. So I'm going to close this out because 1Password integration isn't a priority today for that primary use case. Thanks!
